# Configuración Base de Rescate
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Información mínima
title: "GIDA Test"
url: "https://nherreno.github.io"
baseurl: "/GIDAWEBPAGE_test-"

# Plugins requeridos
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Ignorar archivos innecesarios
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - vendor