# Configuraci贸n GIDA UNAL
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Informaci贸n
title: "GIDA UNAL"
name: "Grupo de Investigaci贸n y Desarrollo Aeroespacial"
url: "https://nherreno.github.io"
baseurl: "/GIDAWEBPAGE_test-"

# Plugins - Esta lista debe ser exacta
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Configuraci贸n por defecto
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false