# Información del sitio
title: "GIDA UNAL"
name: "Grupo de Investigación y Desarrollo Aeroespacial"
description: "Investigación, desarrollo y divulgación de ciencias aeroespaciales en la Universidad Nacional de Colombia."
url: "https://nherreno.github.io"
baseurl: "/GIDAWEBPAGE_test-"

# Configuración del Sidebar (Quitar el modo "persona")
author:
  name: "GIDA - Sede Bogotá"
  location: "Bogotá, Colombia"
  bio: "Desarrollo tecnológico en cohetería y sistemas satelitales."
  links:
    - label: "Web UNAL"
      icon: "fas fa-fw fa-university"
      url: "https://unal.edu.co"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nherreno"

# Desactivar el sidebar de autor por defecto en todas las páginas 
# (Para que el sitio se vea más ancho y profesional)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true # Esto lo dejamos solo para noticias/blogs
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false # FALSO para páginas institucionales (Home, Proyectos)